### ISSUE TITLE
Travis CI usage on OSX is deprecated

### ISSUE THREAD

**Issue by beckermr** [conda-forge/gdb-feedstock#52]
FYI, due to how Travis CI accounts for open-source build minutes, we have deprecated using it for platforms other than those in their partner queue (ppc64le, aarch64, s390x). 

You all are heavy users of Travis on OSX and so we need to find an alternative solution. 

I know this is a pain and we're sorry this is not as convenient as it used to be. 

cc @conda-forge/core

**Comment by beckermr** [comment]
xref: https://github.com/conda-forge/gdb-feedstock/pull/51

**Comment by phil-blain** [comment]
That's OK, I knew this day would come eventually. I worked with the upstream GDB project to try to fix the bug that was keeping us stuck at macOS 10.13 and thus Travis. I'll transition to Azure in #51 when I get to it. 

BTW, a rerender in #51 caused the ppc64le build to also move to Azure, where our "smoke test" of simply running a "hello world" under GDB does not work as `ptrace` does not work under emulation. Would core recommended we keep ppc64le on Travis, or just skip the test under emulation ?...

**Comment by beckermr** [comment]
Thank you so much for working on this. We know it is a pain. 

Once we fix the credits issue, ppc on Travis will be fine.

**Comment by phil-blain** [comment]
Super, thanks. Is there an issue I can follow regarding this (credits/ppc on Travis) ?

**Comment by beckermr** [comment]
Not yet. I will make one later.

**Comment by jakirkham** [comment]
Thanks Philippe! 🙏
