### ISSUE TITLE
Building on macOS

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/gdb-feedstock#7]
Would be great to have a build of `gdb` on macOS.

Not sure what issues were encountered trying to solve this previously, but references to things tried, build logs, failure snippets, etc. would be useful. Admittedly these might be quite old and/or hard to find, but anything on this front would help.

**Comment by gqmelo** [comment]
So going back a long time ago to the [staged-recipes PR](https://github.com/conda-forge/staged-recipes/pull/1676#issuecomment-250063664), I remember that I could actually make it build on MacOS, but could not test it because the binary needs to be signed.

Unfortunately I think I cleaned up the recipe a little bit and could not find the first version. So you may need to add some dependencies, but it should not be hard.

**Comment by phil-blain** [comment]
I'm really interested in this; building gdb (from Homebrew) took 25 minutes on my mac so a binary package would be ideal ! 

From what I understand to be able to test the binary on the CI, each step of the procedure here
https://sourceware.org/gdb/wiki/PermissionsDarwin would have to be done by command line. I think that would be feasible using the `security` command but I have yet to determine each step.
Also, I guess that after `conda install gdb` the gdb binary would have to be code-signed on the installation machine. Brew handles that with a "Caveats" section during installation : 

~~~bash
$ brew install gdb
==> Downloading https://ftp.gnu.org/gnu/gdb/gdb-8.3.tar.xz
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/gdb/8.3 --enable-targets=all --with-python=/usr --disable-binutils
==> make
==> make install-gdb
==> Caveats
gdb requires special privileges to access Mach ports.
You will need to codesign the binary. For instructions, see:

  https://sourceware.org/gdb/wiki/BuildingOnDarwin

On 10.12 (Sierra) or later with SIP, you need to run this:

  echo "set startup-with-shell off" >> ~/.gdbinit
~~~

Is that kind of post-installation message possible with conda ?

**Comment by marcelotrevisani** [comment]
> I'm really interested in this; building gdb (from Homebrew) took 25 minutes on my mac so a binary package would be ideal !
> 
> From what I understand to be able to test the binary on the CI, each step of the procedure here
> https://sourceware.org/gdb/wiki/PermissionsDarwin would have to be done by command line. I think that would be feasible using the `security` command but I have yet to determine each step.
> Also, I guess that after `conda install gdb` the gdb binary would have to be code-signed on the installation machine. Brew handles that with a "Caveats" section during installation :
> 
> ```shell
> $ brew install gdb
> ==> Downloading https://ftp.gnu.org/gnu/gdb/gdb-8.3.tar.xz
> ######################################################################## 100.0%
> ==> ./configure --prefix=/usr/local/Cellar/gdb/8.3 --enable-targets=all --with-python=/usr --disable-binutils
> ==> make
> ==> make install-gdb
> ==> Caveats
> gdb requires special privileges to access Mach ports.
> You will need to codesign the binary. For instructions, see:
> 
>   https://sourceware.org/gdb/wiki/BuildingOnDarwin
> 
> On 10.12 (Sierra) or later with SIP, you need to run this:
> 
>   echo "set startup-with-shell off" >> ~/.gdbinit
> ```
> 
> Is that kind of post-installation message possible with conda ?

Yes, that is possible with an activate script, you can see something similar on gdal feedstock.
That would be interesting indeed. However, osx is not my cup of tea, we are very open to a new PR to add it to osx as well! :)

**Comment by phil-blain** [comment]
> From what I understand to be able to test the binary on the CI, each step of the procedure here
https://sourceware.org/gdb/wiki/PermissionsDarwin would have to be done by command line.

I found out the LLDB project actually has a script that automates the codesigning procedure, so it looks like it is feasible : https://github.com/llvm-mirror/lldb/blob/master/scripts/macos-setup-codesign.sh
